microphone:
  name: Respeaker 4 Mic Array (UAC1.0) # microphone name
  rate: 16000 # sampling rate of microphone
  length: 256 # the number of sampling data in fft
               # length = rate / frequency resolution of fft

publish_spectrogram:
  cutoff_rate: 4500 # cutoff the high frequency data from fft result
                    # please set the number less than (10 * frequency resolution of fft)
  hit_volume_threshold: 0.07 # volume threshold to detect sound. set best threshold for your microphone
  time_to_listen: 1.5 # total time of horizontal axis of spectrogram

classify_spectrogram_ros:
  model: $(find sound_classification)/scripts/result/model_best.npz # weights for sound classification
